[package]
name = "web-sdl2-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bytemuck = "1.13.1"
glam = { version = "0.23.0", features = ["bytemuck"] }
sdl2 = "0.35.2"
tinyjson = "2.5.1"

[build-dependencies]
gl_generator = "0.14.0"
